#+OPTIONS: ':nil *:t -:t ::t <:t H:1 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: MIDAS
#+DATE: <2017-12-11 Thu>
#+AUTHOR: Richard Longland
#+EMAIL: longland@X1Carbon
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 24.5.1 (Org mode 9.0.5)

* Install
  This is based on the new install instructions on the TRIUMF website
** Environment
   Make sure you have something like the following set in .bashrc
   #+BEGIN_SRC sh
   ## MIDAS
   export MIDASSYS=/home/daq/midas/packages/midas
   export PATH=$PATH:$MIDASSYS/bin
   export MIDAS_EXPTAB=/home/daq/midas/online/exptab
   export MIDAS_EXPT_NAME=v785
   export ROOTANASYS=/home/daq/midas/packages/rootana
   #+END_SRC
** Package installation
   + Get the source
     #+BEGIN_SRC sh
     cd ~
     mkdir -p midas/packages
     cd midas/packages
     git clone https://bitbucket.org/tmidas/midas --recursive
     cd midas
     #+END_SRC
   + Checkout a release version
     #+BEGIN_SRC sh
     git checkout midas-2019-06-b
     #+END_SRC
   + Build midas
     #+BEGIN_SRC sh
     mkdir build
     cd build
     cmake ..
     make
     make install
     #+END_SRC
   + Rootana is needed
     #+BEGIN_SRC sh
     cd $HOME/midas/packages
     git clone https://bitbucket.org/tmidas/rootana
     cd rootana
     make
     #+END_SRC
   + Install JSROOT just in case we need it (for browser views of root files)
     #+BEGIN_SRC sh
     cd $HOME/midas/packages
     git clone https://github.com/linev/jsroot.git
     #+END_SRC
** Setting up experiment structure
   + See if the exptab file below already exists. If not: 
     #+BEGIN_SRC sh
     cd
     mkdir midas/online
     cd midas/online
     cat > exptab
       v785 /home/daq/midas/online/data/v785 daq
     #+END_SRC
     (Press ctrl-c to exit the cat command)
   + Make the directory structures (data is a link to the storage partition)
     #+BEGIN_SRC sh
     cd ~/midas/online
     mkdir -p /data/midas/data
     ln -s /data/midas/data data
     mkdir elog
     mkdir history
     mkdir src
     #+END_SRC
   + To separate experiments I like to create a link in the data directory ([[StorageLinks][see below for more]])
     #+BEGIN_SRC sh
     cd /data/midas/data
     mkdir TestExperiment
     ln -s TestExperiment v785
     ls -l
     #+END_SRC
   + Test the system
     #+BEGIN_SRC sh
     odbedit
     ls
     #+END_SRC
     You should see the following:
     #+BEGIN_SRC sh
     [local:v785:S]/>ls
     Experiment                      
     System                          
     Programs                        
     Logger                          
     Runinfo                         
     Alarms                          
     [local:v785:S]/>
     #+END_SRC
     Press ~ctrl-c~ to exit
** Download the Enge MIDAS DAQ
   + The DAQ is already written (probably with some improvements that should be made)
     #+BEGIN_SRC sh
     cd $HOME/midas/online/src
     git clone http://engesrv.physics.ncsu.edu/midas/v785.git
     cd v785
     make clean
     #+END_SRC
   + With the new version of MIDAS, some work need to be done to get the DAQ working. The following command may fail
     #+BEGIN_SRC sh
     make
     #+END_SRC
     If so, see: https://midas.triumf.ca/MidasWiki/index.php/Changelog#Upgrade_guide
   + The corrected version is on the c++ branch:
     #+BEGIN_SRC sh
     git checkout c++
     make clean
     make
     #+END_SRC
** Password security
   + Run the httpd server
     #+BEGIN_SRC sh
     mhttpd
     #+END_SRC
   + The first time you run the MIDAS http server it'll give you some errors. Do what it tells you:
     #+BEGIN_SRC sh
     cd $MIDASSYS
     openssl req -new -nodes -newkey rsa:2048 -sha256 -out ssl_cert.csr -keyout ssl_cert.key -subj "/C=/ST=/L=/O=midas/OU=mhttpd/CN=localhost"
     openssl x509 -req -days 365 -sha256 -in ssl_cert.csr -signkey ssl_cert.key -out ssl_cert.pem
     cat ssl_cert.key >> ssl_cert.pem
     #+END_SRC
   + Try again ~mhhtpd~
* Switching over to MIDAS from NSCLDAQ
** Hardware
   + Take veto (O1) out of VM-USB module in VME crate
   + Plug the twisted pair cable into busy of ADC (red on bottom)
** Software
*** General Notes <<StorageLinks>>:
    + Data is saved in  ~/home/daq/midas/online~
      + link points to ~/data/midas/data~
    + Run files saved at ~v785~ (symbolic link)
    + v785 points to specific directory (eg. ~/2017-11-14_DAQTests~)
    + Actual DAQ code is in ~/home/daq/midas/online/src/v785~
      + 'v785' is the experiment name
*** Starting the DAQ
    + See what experiment is active
      #+BEGIN_SRC sh
      echo $MIDAS_EXPT_NAME
      #+END_SRC
    + If it's not 'v785', do this:
      #+BEGIN_SRC sh
      export MIDAS_EXPT_NAME=v785
      #+END_SRC
    + Move into the experiement directory
      #+BEGIN_SRC sh
      cd /home/daq/midas/online/src/v785
      #+END_SRC
    + To start the DAQ
      #+BEGIN_SRC sh
      ./start_daq.sh
      #+END_SRC
      The analyzer should pop up (there may be a couple of errors but
      ignore them)
    + Open google chrome
      + Click on MIDAS bookmark
      + If there's an error about security, go to Advanced -> proceed anyway
      + Username: daq
      + Password: the usual ;)
      + Click on "EngeRun" to go to the Enge-specific run page
      + Logger and analyzer should be green
      + Click on "ODB" at the top
      + Click on "Run info"
      + Click on "Run Number", set to zero if this is a new experiment
    + Start the frontend
      + In a terminal, open a new window or tab
	#+BEGIN_SRC sh
	cd /home/daq/midas/online/src/v785
	./sync
	ssh engesbc
	cd midas/online/src/v785
	make clean
	make
	./start_fe.sh
	#+END_SRC
	You should see a bunch of things in the terminal that make it
        look like everything's working (running clock, run status, etc.)
      + "Frontend" should now be green in browser
    + Start the root analyzer
      + Go to the original terminal
	#+BEGIN_SRC sh
	cd rootana
	./anaDistplay.exe
	#+END_SRC
      + Close the graph window that opened
      + Resize the other window (silly fix for window wize issues)
      + "Root Analyzer" should now be green in browser
*** Quit the DAQ
    + Quit root analyzer by pressing the "quit" button
    + Go to ~src/v785~ directory
      #+BEGIN_SRC sh
      ./kill_daq.sh
      #+END_SRC
    + F5 on webpage should show that it disappeared
